package com.sherif.womenabsworkoutsecit.fragments;

import android.annotation.SuppressLint;
import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.PorterDuff;
import android.os.Bundle;
import android.preference.PreferenceManager;
import android.util.DisplayMetrics;
import android.view.Display;
import android.view.LayoutInflater;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;
import androidx.fragment.app.Fragment;

import com.facebook.ads.AdChoicesView;
import com.google.android.gms.ads.AdListener;
import com.google.android.gms.ads.AdRequest;
import com.google.android.gms.ads.InterstitialAd;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.sherif.womenabsworkoutsecit.R;
import com.sherif.womenabsworkoutsecit.activities.AdmobAds;

public class DailyMeal extends Fragment {
    public static final String TAG = "DailyMeal";

    /* renamed from: a  reason: collision with root package name */
    public Context f894a;
    public AdRequest adRequest;
    public LayoutInflater ad_inflater;
    public AdmobAds admobAdsObject = null;
    public Boolean complete;
    public FloatingActionButton completed;
    public InterstitialAd interstitial;
    public Button mBtnStdDiet;
    public Button mBtnVegDiet;
    public LinearLayout mLayoutStdDiet;
    public LinearLayout mLayoutVegDiet;
    public SharedPreferences mSharedPreferences;
    public SharedPreferences.Editor prefsEditor;
    public int screenHeight;
    public int screenWidth;
    public ScrollView scrollstddietfood;
    public ScrollView scrollvegdietfood;
    public AdChoicesView stddiet_adChoicesView;
    public LinearLayout stddiet_nativeAdContainer = null;
    public Boolean stddietenabled;
    public AdChoicesView vegdiet_adChoicesView;
    public LinearLayout vegdiet_nativeAdContainer = null;
    public Boolean vegdietenabled;


    public void requestNewInterstitial() {
        this.interstitial.loadAd(this.adRequest);
    }

    private void setAdmodAds() {
        this.interstitial = new InterstitialAd(getActivity());
        this.interstitial.setAdUnitId(getString(R.string.g_inr));
        this.adRequest = new AdRequest.Builder().build();
        this.interstitial.setAdListener(new AdListener() {
            public void onAdClosed() {
                super.onAdClosed();
                DailyMeal.this.requestNewInterstitial();
            }
        });
        requestNewInterstitial();
    }

    public void onCreate(Bundle bundle) {
        super.onCreate(bundle);
        this.f894a = getActivity();
    }


    public View onCreateView(LayoutInflater layoutInflater, ViewGroup viewGroup, Bundle bundle) {
        TextView textView;
        TextView textView2;
        String str;
        TextView textView3;
        String str2;
        TextView textView4;
        String str3;
        DailyMeal dailyMeal = this;
        setAdmodAds();
        View inflate = layoutInflater.inflate(R.layout.layout_dailymeal, viewGroup, false);
        inflate.setTag("DailyMeal");
        getArguments().getInt("DAY");
        Display defaultDisplay = ((WindowManager) getActivity().getSystemService(Context.WINDOW_SERVICE)).getDefaultDisplay();
        DisplayMetrics displayMetrics = new DisplayMetrics();
        defaultDisplay.getMetrics(displayMetrics);
        dailyMeal.screenWidth = displayMetrics.widthPixels;
        dailyMeal.screenHeight = displayMetrics.heightPixels;
        Toolbar toolbar = (Toolbar) inflate.findViewById(R.id.toolbar);
        TextView textView5 = (TextView) toolbar.findViewById(R.id.tittletext);
        StringBuilder sb = new StringBuilder();
        sb.append(getResources().getString(R.string.day));
        sb.append(getArguments().getInt("DAY"));
        textView5.setText(sb.toString());
        ((AppCompatActivity) getActivity()).setSupportActionBar(toolbar);
        ((AppCompatActivity) getActivity()).getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        ((AppCompatActivity) getActivity()).getSupportActionBar().setDisplayShowHomeEnabled(true);
        dailyMeal.setHasOptionsMenu(true);
        toolbar.getNavigationIcon().mutate().setColorFilter(getResources().getColor(R.color.black), PorterDuff.Mode.SRC_IN);
        dailyMeal.scrollstddietfood = (ScrollView) inflate.findViewById(R.id.scrollstddietfood);
        dailyMeal.scrollvegdietfood = (ScrollView) inflate.findViewById(R.id.scrollvegdietfood);
        dailyMeal.mSharedPreferences = PreferenceManager.getDefaultSharedPreferences(getActivity().getApplicationContext());
        dailyMeal.prefsEditor = dailyMeal.mSharedPreferences.edit();
        StringBuilder sb2 = new StringBuilder();
        sb2.append("DAY_");
        sb2.append(getArguments().getInt("DAY"));
        sb2.append("_CHECKED");
        String sb3 = sb2.toString();
        StringBuilder sb4 = new StringBuilder();
        sb4.append("DAY_");
        sb4.append(getArguments().getInt("DAY"));
        sb4.append("_STDDIET");
        String sb5 = sb4.toString();
        StringBuilder sb6 = new StringBuilder();
        sb6.append("DAY_");
        sb6.append(getArguments().getInt("DAY"));
        sb6.append("_VEGDIET");
        String sb7 = sb6.toString();
        dailyMeal.complete = Boolean.valueOf(dailyMeal.mSharedPreferences.getBoolean(sb3, false));
        dailyMeal.stddietenabled = Boolean.valueOf(dailyMeal.mSharedPreferences.getBoolean(sb5, false));
        dailyMeal.vegdietenabled = Boolean.valueOf(dailyMeal.mSharedPreferences.getBoolean(sb7, false));
        dailyMeal.completed = (FloatingActionButton) inflate.findViewById(R.id.fab);

        dailyMeal.mBtnStdDiet = (Button) inflate.findViewById(R.id.Stddiet);
        dailyMeal.mBtnVegDiet = (Button) inflate.findViewById(R.id.vegdiet);

        mBtnStdDiet.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {
//                mBtnStdDiet.setTextColor(R.color.blue);
//                mBtnVegDiet.setTextColor(R.color.black);
//                scrollstddietfood.setVisibility(View.VISIBLE);
//                scrollvegdietfood.setVisibility(View.GONE);

                if (scrollstddietfood.getVisibility() == View.VISIBLE)
                {

                    scrollvegdietfood.setVisibility(View.GONE);
                    scrollstddietfood.setVisibility(View.VISIBLE);
                    mBtnStdDiet.setTextColor(getResources().getColor(R.color.white));
                    mBtnVegDiet.setTextColor(getResources().getColor(R.color.black));
                    mBtnStdDiet.setBackground(getResources().getDrawable(R.drawable.a2_grad));
                    mBtnVegDiet.setBackground(getResources().getDrawable(R.drawable.corner1));
                }
                else
                {
                    scrollvegdietfood.setVisibility(View.GONE);
                    scrollstddietfood.setVisibility(View.VISIBLE);
                    mBtnStdDiet.setTextColor(getResources().getColor(R.color.white));
                    mBtnVegDiet.setTextColor(getResources().getColor(R.color.black));
                    mBtnStdDiet.setBackground(getResources().getDrawable(R.drawable.a2_grad));
                    mBtnVegDiet.setBackground(getResources().getDrawable(R.drawable.corner1));
                }



            }
        });
        mBtnVegDiet.setOnClickListener(new View.OnClickListener() {
            @SuppressLint("ResourceAsColor")
            @Override
            public void onClick(View v) {
//                mBtnStdDiet.setTextColor(R.color.black);
//                mBtnVegDiet.setTextColor(R.color.blue);
//                scrollstddietfood.setVisibility(View.GONE);
//                scrollvegdietfood.setVisibility(View.VISIBLE);


                if (scrollvegdietfood.getVisibility() == View.GONE)
                {

                    scrollvegdietfood.setVisibility(View.VISIBLE);
                    scrollstddietfood.setVisibility(View.GONE);
                    mBtnStdDiet.setTextColor(getResources().getColor(R.color.black));
                    mBtnVegDiet.setTextColor(getResources().getColor(R.color.white));
                    mBtnVegDiet.setBackground(getResources().getDrawable(R.drawable.a2_grad));
                    mBtnStdDiet.setBackground(getResources().getDrawable(R.drawable.corner1));
                }
                else {
                    scrollvegdietfood.setVisibility(View.VISIBLE);
                    scrollstddietfood.setVisibility(View.GONE);
                    mBtnStdDiet.setTextColor(getResources().getColor(R.color.black));
                    mBtnVegDiet.setTextColor(getResources().getColor(R.color.white));
                    mBtnVegDiet.setBackground(getResources().getDrawable(R.drawable.a2_grad));
                    mBtnStdDiet.setBackground(getResources().getDrawable(R.drawable.corner1));
                }

            }
        });










        dailyMeal.mLayoutStdDiet = (LinearLayout) inflate.findViewById(R.id.stddietfood);
        dailyMeal.mLayoutVegDiet = (LinearLayout) inflate.findViewById(R.id.vegdietfood);
        TextView textView6 = (TextView) inflate.findViewById(R.id.brkfast1);
        TextView textView7 = (TextView) inflate.findViewById(R.id.brkfast2);
        TextView textView8 = (TextView) inflate.findViewById(R.id.lunch1);
        TextView textView9 = (TextView) inflate.findViewById(R.id.lunch2);
        TextView textView10 = (TextView) inflate.findViewById(R.id.snack1);
        TextView textView11 = (TextView) inflate.findViewById(R.id.snack2);
        TextView textView12 = (TextView) inflate.findViewById(R.id.snack3);
        TextView textView13 = (TextView) inflate.findViewById(R.id.dinner1);
        TextView textView14 = (TextView) inflate.findViewById(R.id.dinner2);
        TextView textView15 = (TextView) inflate.findViewById(R.id.dinner3);
        TextView textView16 = (TextView) inflate.findViewById(R.id.vegbrkfast1);
        String str4 = sb3;
        TextView textView17 = (TextView) inflate.findViewById(R.id.vegbrkfast2);
        String str5 = sb5;
        TextView textView18 = (TextView) inflate.findViewById(R.id.veglunch1);
        String str6 = sb7;
        TextView textView19 = (TextView) inflate.findViewById(R.id.veglunch2);
        TextView textView20 = (TextView) inflate.findViewById(R.id.vegsnack1);
        TextView textView21 = (TextView) inflate.findViewById(R.id.vegsnack2);
        TextView textView22 = (TextView) inflate.findViewById(R.id.vegsnack3);
        TextView textView23 = (TextView) inflate.findViewById(R.id.vegdinner1);
        TextView textView24 = (TextView) inflate.findViewById(R.id.vegdinner2);
        View view = inflate;
        TextView textView25 = (TextView) inflate.findViewById(R.id.vegdinner3);
        dailyMeal.ad_inflater = (LayoutInflater) getActivity().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        switch (getArguments().getInt("DAY")) {
            case 1:
                TextView textView26 = textView19;
                TextView textView27 = textView20;
                TextView textView28 = textView22;
                TextView textView29 = textView23;
                TextView textView30 = textView24;
                textView6.setText(getResources().getString(R.string.twoboiledeggwhites));
                textView7.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Redricewithsteamcookedtuna));
                textView9.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView10.setText(getResources().getString(R.string.onecupofgreentea));
                textView11.setText(getResources().getString(R.string.fouroatmealcookies));
                textView12.setText(getResources().getString(R.string.fivealmonds));
                textView13.setText(getResources().getString(R.string.steamcookedchickenbreasts));
                textView14.setText(getResources().getString(R.string.Fruitsalad));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.twoboiledeggwhites));
                textView17.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Redricewithmushroom));
                textView26.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView20.setText(getResources().getString(R.string.onecupofgreentea));
                textView21.setText(getResources().getString(R.string.fouroatmealcookies));
                textView28.setText(getResources().getString(R.string.fivealmonds));
                textView29.setText(getResources().getString(R.string.Vegetablesoup));
                textView30.setText(getResources().getString(R.string.Grapes));
                textView25.setText(getResources().getString(R.string.greekyogurt));
                break;
            case 2:
                TextView textView31 = textView19;
                TextView textView32 = textView20;
                TextView textView33 = textView22;
                TextView textView34 = textView23;
                TextView textView35 = textView24;
                TextView textView36 = textView25;
                textView6.setText(getResources().getString(R.string.onescrambledegg));
                textView7.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Wholewheatpastawithveggies));
                textView9.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView10.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView11.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView12.setText(getResources().getString(R.string.fourWalnuts));
                textView13.setText(getResources().getString(R.string.Chickensoup));
                textView14.setText(getResources().getString(R.string.Pineappleslicesorgrapes));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.onescrambledegg));
                textView17.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Wholewheatpastawithveggies));
                textView31.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView20.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView21.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView33.setText(getResources().getString(R.string.fourWalnuts));
                textView34.setText(getResources().getString(R.string.Tomatosoup));
                textView35.setText(getResources().getString(R.string.Fruitsalad));
                textView = textView36;
                break;
            case 3:
                TextView textView37 = textView19;
                TextView textView38 = textView20;
                TextView textView39 = textView22;
                TextView textView40 = textView23;
                TextView textView41 = textView24;
                textView6.setText(getResources().getString(R.string.twoboiledeggwhites));
                textView7.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.WholewheatchickenwrapChickenbreastslettucetomatoyogurtsauce));
                textView9.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView10.setText(getResources().getString(R.string.oneglassofamlajuice));
                textView11.setText(getResources().getString(R.string.fourslicesofpineapple));
                textView12.setText(getResources().getString(R.string.fivealmonds));
                textView13.setText(getResources().getString(R.string.Steamcookedleanbeef));
                textView14.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView15.setText(getResources().getString(R.string.greekyogurt));
                textView16.setText(getResources().getString(R.string.twoboiledeggwhites));
                textView17.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.WholewheatvegetablewrapTomatoonioncucumberspinachcheese));
                textView37.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView20.setText(getResources().getString(R.string.oneglassofamlajuice));
                textView21.setText(getResources().getString(R.string.fourslicesofpineapple));
                textView39.setText(getResources().getString(R.string.fivealmonds));
                textView40.setText(getResources().getString(R.string.leafygreenssoupbroccolispinachlettuce));
                str2 = getResources().getString(R.string.Pineappleslices);
                textView3 = textView41;
                break;
            case 4:
                TextView textView42 = textView19;
                TextView textView43 = textView20;
                TextView textView44 = textView22;
                TextView textView45 = textView23;
                TextView textView46 = textView24;
                textView6.setText(getResources().getString(R.string.twoscrambledeggs));
                textView7.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Wholewheatpastawithsteamcookedsalmon));
                textView9.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView10.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView11.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView12.setText(getResources().getString(R.string.fourWalnuts));
                textView13.setText(getResources().getString(R.string.Vegetablesoup));
                textView14.setText(getResources().getString(R.string.Chickenbreasts));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.twoscrambledeggs));
                textView17.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Wholewheatpastawithbroccoli));
                textView42.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView20.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView21.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView44.setText(getResources().getString(R.string.fourWalnuts));
                textView45.setText(getResources().getString(R.string.Vegetablesoup));
                str3 = getResources().getString(R.string.Grapes);
                textView4 = textView46;
                break;
            case 5:
                TextView textView47 = textView19;
                TextView textView48 = textView20;
                TextView textView49 = textView22;
                TextView textView50 = textView23;
                TextView textView51 = textView24;
                textView6.setText(getResources().getString(R.string.twoboiledeggwhites));
                textView7.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Redricewithsteamcookedtuna));
                textView9.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView10.setText(getResources().getString(R.string.onecupofgreentea));
                textView11.setText(getResources().getString(R.string.fouroatmealcookies));
                textView12.setText(getResources().getString(R.string.fivealmonds));
                textView13.setText(getResources().getString(R.string.steamcookedchickenbreasts));
                textView14.setText(getResources().getString(R.string.Fruitsalad));
                textView15.setText(getResources().getString(R.string.greekyogurt));
                textView16.setText(getResources().getString(R.string.twoboiledeggwhites));
                textView17.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Redricewithleafygreenspinachbroccoli));
                textView47.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView20.setText(getResources().getString(R.string.onecupofgreentea));
                textView21.setText(getResources().getString(R.string.fouroatmealcookies));
                textView49.setText(getResources().getString(R.string.fivealmonds));
                textView50.setText(getResources().getString(R.string.Tomatosoup));
                str3 = getResources().getString(R.string.Fruitsalad);
                textView4 = textView51;
                break;
            case 6:
                TextView textView52 = textView19;
                TextView textView53 = textView20;
                TextView textView54 = textView22;
                TextView textView55 = textView23;
                TextView textView56 = textView24;
                TextView textView57 = textView25;
                textView6.setText(getResources().getString(R.string.onescrambledegg));
                textView7.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Wholewheatpastawithbroccoli));
                textView9.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView10.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView11.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView12.setText(getResources().getString(R.string.fourWalnuts));
                textView13.setText(getResources().getString(R.string.Chickensoup));
                textView14.setText(getResources().getString(R.string.threePineappleslicesorgrapes));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.onescrambledegg));
                textView17.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Wholewheatpastawithbroccoli));
                textView52.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView20.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView21.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView54.setText(getResources().getString(R.string.fourWalnuts));
                textView55.setText(getResources().getString(R.string.leafygreenssoupbroccolispinachlettuce));
                textView56.setText(getResources().getString(R.string.Pineappleslices));
                textView = textView57;
                break;
            case 7:
                TextView textView58 = textView19;
                TextView textView59 = textView20;
                TextView textView60 = textView22;
                TextView textView61 = textView23;
                TextView textView62 = textView24;
                textView6.setText(getResources().getString(R.string.twoboiledeggwhites));
                textView7.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.WholewheatfishwrapSteamcookedtunalettucetomatoyogurtsauce));
                textView9.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView10.setText(getResources().getString(R.string.oneglassofamlajuice));
                textView11.setText(getResources().getString(R.string.threeslicesofpineapple));
                textView12.setText(getResources().getString(R.string.fivealmonds));
                textView13.setText(getResources().getString(R.string.Steamcookedleanbeef));
                textView14.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.twoboiledeggwhites));
                textView17.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Redricewithmushroom));
                textView58.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView20.setText(getResources().getString(R.string.oneglassofamlajuice));
                textView21.setText(getResources().getString(R.string.threeslicesofpineapple));
                textView60.setText(getResources().getString(R.string.fivealmonds));
                textView61.setText(getResources().getString(R.string.Vegetablesoup));
                str2 = getResources().getString(R.string.Grapes);
                textView3 = textView62;
                break;
            case 8:
                TextView textView63 = textView19;
                TextView textView64 = textView20;
                TextView textView65 = textView22;
                TextView textView66 = textView23;
                TextView textView67 = textView24;
                TextView textView68 = textView25;
                textView6.setText(getResources().getString(R.string.twoscrambledeggs));
                textView7.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.RedricewithsteamcookedLeanbeef));
                textView9.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView10.setText(getResources().getString(R.string.onecupofgreentea));
                textView11.setText(getResources().getString(R.string.fiveoatmealcookies));
                textView12.setText(getResources().getString(R.string.sixalmonds));
                textView13.setText(getResources().getString(R.string.steamcookedchickenbreasts));
                textView14.setText(getResources().getString(R.string.Fruitsalad));
                textView15.setText(getResources().getString(R.string.greekyogurt));
                textView16.setText(getResources().getString(R.string.twoscrambledeggs));
                textView17.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.WholewheatvegetablewrapTomatoonioncucumberspinachcheese));
                textView63.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView20.setText(getResources().getString(R.string.onecupofgreentea));
                textView21.setText(getResources().getString(R.string.fiveoatmealcookies));
                textView65.setText(getResources().getString(R.string.sixalmonds));
                textView66.setText(getResources().getString(R.string.Tomatosoup));
                textView67.setText(getResources().getString(R.string.Fruitsalad));
                textView = textView68;
                break;
            case 9:
                TextView textView69 = textView19;
                TextView textView70 = textView20;
                TextView textView71 = textView22;
                TextView textView72 = textView23;
                TextView textView73 = textView24;
                textView6.setText(getResources().getString(R.string.threeboiledeggwhites));
                textView7.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Wholewheatpastawithsteamcookedsalmon));
                textView9.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView10.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView11.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView12.setText(getResources().getString(R.string.fourWalnuts));
                textView13.setText(getResources().getString(R.string.Chickensoup));
                textView14.setText(getResources().getString(R.string.threePineappleslicesorgrapes));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.threeboiledeggwhites));
                textView17.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Wholewheatpastawithbroccoli));
                textView69.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView20.setText(getResources().getString(R.string.oneglassofamlajuice));
                textView21.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView71.setText(getResources().getString(R.string.fivewalnuts));
                textView72.setText(getResources().getString(R.string.leafygreenssoupbroccolispinachlettuce));
                str2 = getResources().getString(R.string.Pineappleslices);
                textView3 = textView73;
                break;
            case 10:
                TextView textView74 = textView19;
                TextView textView75 = textView20;
                TextView textView76 = textView22;
                TextView textView77 = textView23;
                TextView textView78 = textView24;
                TextView textView79 = textView25;
                textView6.setText(getResources().getString(R.string.onescrambledegg));
                textView7.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.WholewheatchickenwrapChickenbreastslettucetomatoyogurtsauce));
                textView9.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView10.setText(getResources().getString(R.string.onecupofgreentea));
                textView11.setText(getResources().getString(R.string.fourslicesofpineapple));
                textView12.setText(getResources().getString(R.string.fivealmonds));
                textView13.setText(getResources().getString(R.string.Steamcookedleanbeef));
                textView14.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.onescrambledegg));
                textView17.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Wholewheatpastawithveggies));
                textView74.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView20.setText(getResources().getString(R.string.onecupofgreentea));
                textView21.setText(getResources().getString(R.string.fourslicesofpineapple));
                textView76.setText(getResources().getString(R.string.sixalmonds));
                textView77.setText(getResources().getString(R.string.Vegetablesoup));
                textView78.setText(getResources().getString(R.string.Grapes));
                textView = textView79;
                break;
            case 11:
                TextView textView80 = textView19;
                TextView textView81 = textView20;
                TextView textView82 = textView22;
                TextView textView83 = textView23;
                TextView textView84 = textView24;
                textView6.setText(getResources().getString(R.string.threeboiledeggwhites));
                textView7.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Wholewheatpastawithveggies));
                textView9.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView10.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView11.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView12.setText(getResources().getString(R.string.sixwalnuts));
                textView13.setText(getResources().getString(R.string.Vegetablesoup));
                textView14.setText(getResources().getString(R.string.Chickenbreasts));
                textView15.setText(getResources().getString(R.string.greekyogurt));
                textView16.setText(getResources().getString(R.string.threeboiledeggwhites));
                textView17.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.WholewheatvegetablewrapTomatoonioncucumberspinachcheese));
                textView80.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView20.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView21.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView82.setText(getResources().getString(R.string.fourWalnuts));
                textView83.setText(getResources().getString(R.string.Tomatosoup));
                str2 = getResources().getString(R.string.Fruitsalad);
                textView3 = textView84;
                break;
            case 12:
                TextView textView85 = textView19;
                TextView textView86 = textView20;
                TextView textView87 = textView22;
                TextView textView88 = textView23;
                TextView textView89 = textView24;
                TextView textView90 = textView25;
                textView6.setText(getResources().getString(R.string.twoscrambledeggs));
                textView7.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Redricewithsteamcookedtuna));
                textView9.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView10.setText(getResources().getString(R.string.onecupofgreentea));
                textView11.setText(getResources().getString(R.string.fouroatmealcookies));
                textView12.setText(getResources().getString(R.string.fivealmonds));
                textView13.setText(getResources().getString(R.string.steamcookedchickenbreasts));
                textView14.setText(getResources().getString(R.string.Fruitsalad));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.twoscrambledeggs));
                textView17.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Redricewithleafygreenspinachbroccoli));
                textView85.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView20.setText(getResources().getString(R.string.onecupofgreentea));
                textView21.setText(getResources().getString(R.string.fouroatmealcookies));
                textView87.setText(getResources().getString(R.string.fivealmonds));
                textView88.setText(getResources().getString(R.string.leafygreenssoupbroccolispinachlettuce));
                textView89.setText(getResources().getString(R.string.Pineappleslices));
                textView = textView90;
                break;
            case 13:
                TextView textView91 = textView19;
                TextView textView92 = textView20;
                TextView textView93 = textView22;
                TextView textView94 = textView23;
                TextView textView95 = textView24;
                textView6.setText(getResources().getString(R.string.threeboiledeggwhites));
                textView7.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.WholewheatfishwrapSteamcookedtunalettucetomatoyogurtsauce));
                textView9.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView10.setText(getResources().getString(R.string.oneglassofamlajuice));
                textView11.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView12.setText(getResources().getString(R.string.sixwalnuts));
                textView13.setText(getResources().getString(R.string.Chickensoup));
                textView14.setText(getResources().getString(R.string.threePineappleslicesorgrapes));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.threeboiledeggwhites));
                textView17.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Wholewheatpastawithveggies));
                textView91.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView20.setText(getResources().getString(R.string.oneglassofamlajuice));
                textView21.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView93.setText(getResources().getString(R.string.fourWalnuts));
                textView94.setText(getResources().getString(R.string.Vegetablesoup));
                str2 = getResources().getString(R.string.Grapes);
                textView3 = textView95;
                break;
            case 14:
                TextView textView96 = textView19;
                TextView textView97 = textView20;
                TextView textView98 = textView22;
                TextView textView99 = textView23;
                TextView textView100 = textView24;
                TextView textView101 = textView25;
                textView6.setText(getResources().getString(R.string.twoboiledeggwhites));
                textView7.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Redricewithsteamcookedchickenbreasts));
                textView9.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView10.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView11.setText(getResources().getString(R.string.fourslicesofpineapple));
                textView12.setText(getResources().getString(R.string.fivealmonds));
                textView13.setText(getResources().getString(R.string.Steamcookedleanbeef));
                textView14.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView15.setText(getResources().getString(R.string.greekyogurt));
                textView16.setText(getResources().getString(R.string.twoboiledeggwhites));
                textView17.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Redricewithmushroom));
                textView96.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView20.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView21.setText(getResources().getString(R.string.fourslicesofpineapple));
                textView98.setText(getResources().getString(R.string.fivealmonds));
                textView99.setText(getResources().getString(R.string.Tomatosoup));
                textView100.setText(getResources().getString(R.string.Fruitsalad));
                textView = textView101;
                break;
            case 15:
                TextView textView102 = textView19;
                TextView textView103 = textView20;
                TextView textView104 = textView22;
                TextView textView105 = textView23;
                TextView textView106 = textView24;
                textView6.setText(getResources().getString(R.string.onescrambledegg));
                textView7.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.WholewheatchickenwrapChickenbreastslettucetomatoyogurtsauce));
                textView9.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView10.setText(getResources().getString(R.string.onecupofgreentea));
                textView11.setText(getResources().getString(R.string.fouroatmealcookies));
                textView12.setText(getResources().getString(R.string.sixalmonds));
                textView13.setText(getResources().getString(R.string.steamcookedchickenbreasts));
                textView14.setText(getResources().getString(R.string.Fruitsalad));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.onescrambledegg));
                textView17.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.WholewheatvegetablewrapTomatoonioncucumberspinachcheese));
                textView102.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView20.setText(getResources().getString(R.string.oneglassofamlajuice));
                textView21.setText(getResources().getString(R.string.fouroatmealcookies));
                textView104.setText(getResources().getString(R.string.fivealmonds));
                textView105.setText(getResources().getString(R.string.leafygreenssoupbroccolispinachlettuce));
                str2 = getResources().getString(R.string.Pineappleslices);
                textView3 = textView106;
                break;
            case 16:
                TextView textView107 = textView19;
                TextView textView108 = textView20;
                TextView textView109 = textView22;
                TextView textView110 = textView23;
                TextView textView111 = textView24;
                TextView textView112 = textView25;
                textView6.setText(getResources().getString(R.string.twoboiledeggwhites));
                textView7.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Wholewheatpastawithsteamcookedsalmon));
                textView9.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView10.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView11.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView12.setText(getResources().getString(R.string.fourWalnuts));
                textView13.setText(getResources().getString(R.string.Chickensoup));
                textView14.setText(getResources().getString(R.string.Pineappleslicesorgrapes));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.threeboiledeggwhites));
                textView17.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Wholewheatpastawithbroccoli));
                textView107.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView20.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView21.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView109.setText(getResources().getString(R.string.fourWalnuts));
                textView110.setText(getResources().getString(R.string.Vegetablesoup));
                textView111.setText(getResources().getString(R.string.Grapes));
                textView = textView112;
                break;
            case 17:
                TextView textView113 = textView19;
                TextView textView114 = textView20;
                TextView textView115 = textView22;
                TextView textView116 = textView23;
                TextView textView117 = textView24;
                TextView textView118 = textView25;
                textView6.setText(getResources().getString(R.string.twoscrambledeggs));
                textView7.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Redricewithsteamcookedtuna));
                textView9.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView10.setText(getResources().getString(R.string.oneglassofamlajuice));
                textView11.setText(getResources().getString(R.string.fourslicesofpineapple));
                textView12.setText(getResources().getString(R.string.fivealmonds));
                textView13.setText(getResources().getString(R.string.Steamcookedleanbeef));
                textView14.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView15.setText(getResources().getString(R.string.greekyogurt));
                textView16.setText(getResources().getString(R.string.twoscrambledeggs));
                textView17.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Redricewithleafygreenspinachbroccoli));
                textView113.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView20.setText(getResources().getString(R.string.oneglassofamlajuice));
                textView21.setText(getResources().getString(R.string.fourslicesofpineapple));
                textView115.setText(getResources().getString(R.string.fivealmonds));
                textView116.setText(getResources().getString(R.string.Tomatosoup));
                textView117.setText(getResources().getString(R.string.Fruitsalad));
                str = getResources().getString(R.string.greekyogurt);
                textView2 = textView118;
                break;
            case 18:
                TextView textView119 = textView19;
                TextView textView120 = textView20;
                TextView textView121 = textView22;
                TextView textView122 = textView23;
                TextView textView123 = textView24;
                TextView textView124 = textView25;
                textView6.setText(getResources().getString(R.string.twoboiledeggwhites));
                textView7.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Wholewheatpastawithsteamcookedsalmon));
                textView9.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView10.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView11.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView12.setText(getResources().getString(R.string.fourWalnuts));
                textView13.setText(getResources().getString(R.string.Vegetablesoup));
                textView14.setText(getResources().getString(R.string.Chickenbreasts));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.threeboiledeggwhites));
                textView17.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.WholewheatvegetablewrapTomatoonioncucumberspinachcheese));
                textView119.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView20.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView21.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView121.setText(getResources().getString(R.string.fourWalnuts));
                textView122.setText(getResources().getString(R.string.leafygreenssoupbroccolispinachlettuce));
                textView123.setText(getResources().getString(R.string.Pineappleslices));
                str = getResources().getString(R.string.greekyogurt);
                textView2 = textView124;
                break;
            case 19:
                TextView textView125 = textView19;
                TextView textView126 = textView20;
                TextView textView127 = textView22;
                TextView textView128 = textView23;
                TextView textView129 = textView24;
                textView6.setText(getResources().getString(R.string.onescrambledegg));
                textView7.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.WholewheatfishwrapSteamcookedtunalettucetomatoyogurtsauce));
                textView9.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView10.setText(getResources().getString(R.string.oneglassofamlajuice));
                textView11.setText(getResources().getString(R.string.fouroatmealcookies));
                textView12.setText(getResources().getString(R.string.sixalmonds));
                textView13.setText(getResources().getString(R.string.steamcookedchickenbreasts));
                textView14.setText(getResources().getString(R.string.Fruitsalad));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.onescrambledegg));
                textView17.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Redricewithmushroom));
                textView125.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView20.setText(getResources().getString(R.string.onecupofgreentea));
                textView21.setText(getResources().getString(R.string.fouroatmealcookies));
                textView127.setText(getResources().getString(R.string.fivealmonds));
                textView128.setText(getResources().getString(R.string.Vegetablesoup));
                str2 = getResources().getString(R.string.Grapes);
                textView3 = textView129;
                break;
            case 20:
                TextView textView130 = textView19;
                TextView textView131 = textView20;
                TextView textView132 = textView22;
                TextView textView133 = textView23;
                TextView textView134 = textView24;
                TextView textView135 = textView25;
                textView6.setText(getResources().getString(R.string.threeboiledeggwhites));
                textView7.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Wholewheatpastawithsteamcookedsalmon));
                textView9.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView10.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView11.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView12.setText(getResources().getString(R.string.fourWalnuts));
                textView13.setText(getResources().getString(R.string.Chickensoup));
                textView14.setText(getResources().getString(R.string.threePineappleslicesorgrapes));
                textView15.setText(getResources().getString(R.string.greekyogurt));
                textView16.setText(getResources().getString(R.string.threeboiledeggwhites));
                textView17.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Wholewheatpastawithbroccoli));
                textView130.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView20.setText(getResources().getString(R.string.onecupofgreentea));
                textView21.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView132.setText(getResources().getString(R.string.fourWalnuts));
                textView133.setText(getResources().getString(R.string.Tomatosoup));
                textView134.setText(getResources().getString(R.string.Fruitsalad));
                textView = textView135;
                break;
            case 21:
                TextView textView136 = textView19;
                TextView textView137 = textView20;
                TextView textView138 = textView22;
                TextView textView139 = textView23;
                TextView textView140 = textView24;
                textView6.setText(getResources().getString(R.string.twoscrambledeggs));
                textView7.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Redricewithsteamcookedchickenbreasts));
                textView9.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView10.setText(getResources().getString(R.string.oneglassofamlajuice));
                textView11.setText(getResources().getString(R.string.threeslicesofpineapple));
                textView12.setText(getResources().getString(R.string.sixalmonds));
                textView13.setText(getResources().getString(R.string.Steamcookedleanbeef));
                textView14.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.twoscrambledeggs));
                textView17.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.WholewheatvegetablewrapTomatoonioncucumberspinachcheese));
                textView136.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView20.setText(getResources().getString(R.string.oneglassofamlajuice));
                textView21.setText(getResources().getString(R.string.threeslicesofpineapple));
                textView138.setText(getResources().getString(R.string.fivealmonds));
                textView139.setText(getResources().getString(R.string.leafygreenssoupbroccolispinachlettuce));
                str2 = getResources().getString(R.string.Pineappleslices);
                textView3 = textView140;
                break;
            case 22:
                TextView textView141 = textView19;
                TextView textView142 = textView20;
                TextView textView143 = textView22;
                TextView textView144 = textView23;
                TextView textView145 = textView24;
                TextView textView146 = textView25;
                textView6.setText(getResources().getString(R.string.fourboiledeggwhites));
                textView7.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.WholewheatfishwrapSteamcookedtunalettucetomatoyogurtsauce));
                textView9.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView10.setText(getResources().getString(R.string.onecupofgreentea));
                textView11.setText(getResources().getString(R.string.fiveoatmealcookies));
                textView12.setText(getResources().getString(R.string.fivealmonds));
                textView13.setText(getResources().getString(R.string.steamcookedchickenbreasts));
                textView14.setText(getResources().getString(R.string.Fruitsalad));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.twoboiledeggwhites));
                textView17.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Redricewithleafygreenspinachbroccoli));
                textView141.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView20.setText(getResources().getString(R.string.onecupofgreentea));
                textView21.setText(getResources().getString(R.string.fiveoatmealcookies));
                textView143.setText(getResources().getString(R.string.fivealmonds));
                textView144.setText(getResources().getString(R.string.Vegetablesoup));
                textView145.setText(getResources().getString(R.string.Grapes));
                textView = textView146;
                break;
            case 23:
                TextView textView147 = textView19;
                TextView textView148 = textView20;
                TextView textView149 = textView22;
                TextView textView150 = textView23;
                TextView textView151 = textView24;
                textView6.setText(getResources().getString(R.string.onescrambledegg));
                textView7.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Wholewheatpastawithbroccoli));
                textView9.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView10.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView11.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView12.setText(getResources().getString(R.string.fivewalnuts));
                textView13.setText(getResources().getString(R.string.Chickensoup));
                textView14.setText(getResources().getString(R.string.threePineappleslicesorgrapes));
                textView15.setText(getResources().getString(R.string.greekyogurt));
                textView16.setText(getResources().getString(R.string.onescrambledegg));
                textView17.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Wholewheatpastawithbroccoli));
                textView147.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView20.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView21.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView149.setText(getResources().getString(R.string.fourWalnuts));
                textView150.setText(getResources().getString(R.string.Tomatosoup));
                str2 = getResources().getString(R.string.Fruitsalad);
                textView3 = textView151;
                break;
            case 24:
                TextView textView152 = textView19;
                TextView textView153 = textView20;
                TextView textView154 = textView22;
                TextView textView155 = textView23;
                TextView textView156 = textView24;
                TextView textView157 = textView25;
                textView6.setText(getResources().getString(R.string.threeboiledeggwhites));
                textView7.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Redricewithsteamcookedtuna));
                textView9.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView10.setText(getResources().getString(R.string.oneglassofamlajuice));
                textView11.setText(getResources().getString(R.string.fourslicesofpineapple));
                textView12.setText(getResources().getString(R.string.fivealmonds));
                textView13.setText(getResources().getString(R.string.Steamcookedleanbeef));
                textView14.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.twoboiledeggwhites));
                textView17.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.WholewheatvegetablewrapTomatoonioncucumberspinachcheese));
                textView152.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView20.setText(getResources().getString(R.string.oneglassofamlajuice));
                textView21.setText(getResources().getString(R.string.fourslicesofpineapple));
                textView154.setText(getResources().getString(R.string.fivealmonds));
                textView155.setText(getResources().getString(R.string.leafygreenssoupbroccolispinachlettuce));
                textView156.setText(getResources().getString(R.string.Pineappleslices));
                textView = textView157;
                break;
            case 25:
                TextView textView158 = textView19;
                TextView textView159 = textView20;
                TextView textView160 = textView22;
                TextView textView161 = textView23;
                TextView textView162 = textView24;
                textView6.setText(getResources().getString(R.string.twoscrambledeggs));
                textView7.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Wholewheatpastawithsteamcookedsalmon));
                textView9.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView10.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView11.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView12.setText(getResources().getString(R.string.fourWalnuts));
                textView13.setText(getResources().getString(R.string.Vegetablesoup));
                textView14.setText(getResources().getString(R.string.Chickenbreasts));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.twoscrambledeggs));
                textView17.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Redricewithmushroom));
                textView158.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView20.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView21.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView160.setText(getResources().getString(R.string.fourWalnuts));
                textView161.setText(getResources().getString(R.string.Vegetablesoup));
                str2 = getResources().getString(R.string.Grapes);
                textView3 = textView162;
                break;
            case 26:
                TextView textView163 = textView19;
                TextView textView164 = textView20;
                TextView textView165 = textView22;
                TextView textView166 = textView23;
                TextView textView167 = textView24;
                textView6.setText(getResources().getString(R.string.threeboiledeggwhites));
                textView7.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.WholewheatchickenwrapChickenbreastslettucetomatoyogurtsauce));
                textView9.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView10.setText(getResources().getString(R.string.onecupofgreentea));
                textView11.setText(getResources().getString(R.string.fouroatmealcookies));
                textView12.setText(getResources().getString(R.string.fivealmonds));
                textView13.setText(getResources().getString(R.string.steamcookedchickenbreasts));
                textView14.setText(getResources().getString(R.string.Fruitsalad));
                textView15.setText(getResources().getString(R.string.greekyogurt));
                textView16.setText(getResources().getString(R.string.twoboiledeggwhites));
                textView17.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Wholewheatpastawithveggies));
                textView163.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView20.setText(getResources().getString(R.string.onecupofgreentea));
                textView21.setText(getResources().getString(R.string.fouroatmealcookies));
                textView165.setText(getResources().getString(R.string.fivealmonds));
                textView166.setText(getResources().getString(R.string.Tomatosoup));
                str3 = getResources().getString(R.string.Fruitsalad);
                textView4 = textView167;
                break;
            case 27:
                TextView textView168 = textView19;
                TextView textView169 = textView20;
                TextView textView170 = textView22;
                TextView textView171 = textView23;
                TextView textView172 = textView24;
                textView6.setText(getResources().getString(R.string.onescrambledegg));
                textView7.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Wholewheatpastawithsteamcookedsalmon));
                textView9.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView10.setText(getResources().getString(R.string.oneglassofamlajuice));
                textView11.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView12.setText(getResources().getString(R.string.fivewalnuts));
                textView13.setText(getResources().getString(R.string.Chickensoup));
                textView14.setText(getResources().getString(R.string.threePineappleslicesorgrapes));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.onescrambledegg));
                textView17.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.WholewheatvegetablewrapTomatoonioncucumberspinachcheese));
                textView168.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView20.setText(getResources().getString(R.string.oneglassofamlajuice));
                textView21.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView170.setText(getResources().getString(R.string.fourWalnuts));
                textView171.setText(getResources().getString(R.string.leafygreenssoupbroccolispinachlettuce));
                str3 = getResources().getString(R.string.Pineappleslices);
                textView4 = textView172;
                break;
            case 28:
                TextView textView173 = textView19;
                TextView textView174 = textView20;
                TextView textView175 = textView22;
                TextView textView176 = textView23;
                TextView textView177 = textView24;
                TextView textView178 = textView25;
                textView6.setText(getResources().getString(R.string.twoboiledeggwhites));
                textView7.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Redricewithsteamcookedtuna));
                textView9.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView10.setText(getResources().getString(R.string.onecupofgreentea));
                textView11.setText(getResources().getString(R.string.fourslicesofpineapple));
                textView12.setText(getResources().getString(R.string.fivealmonds));
                textView13.setText(getResources().getString(R.string.steamcookedchickenbreasts));
                textView14.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.twoboiledeggwhites));
                textView17.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Redricewithmushroom));
                textView173.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView20.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView21.setText(getResources().getString(R.string.fourslicesofpineapple));
                textView175.setText(getResources().getString(R.string.fivealmonds));
                textView176.setText(getResources().getString(R.string.Vegetablesoup));
                textView177.setText(getResources().getString(R.string.Grapes));
                textView = textView178;
                break;
            case 29:
                TextView textView179 = textView19;
                TextView textView180 = textView20;
                TextView textView181 = textView22;
                TextView textView182 = textView23;
                TextView textView183 = textView24;
                textView6.setText(getResources().getString(R.string.onescrambledegg));
                textView7.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Wholewheatpastawithveggies));
                textView9.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView10.setText(getResources().getString(R.string.onecupofgreentea));
                textView11.setText(getResources().getString(R.string.fouroatmealcookies));
                textView12.setText(getResources().getString(R.string.fivealmonds));
                textView13.setText(getResources().getString(R.string.steamcookedchickenbreasts));
                textView14.setText(getResources().getString(R.string.Fruitsalad));
                textView15.setText(getResources().getString(R.string.greekyogurt));
                textView16.setText(getResources().getString(R.string.onescrambledegg));
                textView17.setText(getResources().getString(R.string.Cornflakeswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.Wholewheatpastawithveggies));
                textView179.setText(getResources().getString(R.string.VegetablesaladCarrotcucumbercabbagelettuce));
                textView20.setText(getResources().getString(R.string.onecupofgreentea));
                textView21.setText(getResources().getString(R.string.fouroatmealcookies));
                textView181.setText(getResources().getString(R.string.fivealmonds));
                textView182.setText(getResources().getString(R.string.Tomatosoup));
                str2 = getResources().getString(R.string.Fruitsalad);
                textView3 = textView183;
                break;
            case 30:
                textView6.setText(getResources().getString(R.string.threeboiledeggwhites));
                textView7.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView8.setText(getResources().getString(R.string.Redricewithsteamcookedtuna));
                textView9.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView10.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView11.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView12.setText(getResources().getString(R.string.fivewalnuts));
                textView13.setText(getResources().getString(R.string.Chickensoup));
                textView14.setText(getResources().getString(R.string.Pineappleslicesorgrapes));
                textView15.setVisibility(View.GONE);
                textView16.setText(getResources().getString(R.string.threeboiledeggwhites));
                textView17.setText(getResources().getString(R.string.Oatswithskimmedmilk));
                textView18.setText(getResources().getString(R.string.WholewheatvegetablewrapTomatoonioncucumberspinachcheese));
                textView19.setText(getResources().getString(R.string.BoiledvegetablesSpinachbeanscabbagetomato));
                textView20.setText(getResources().getString(R.string.oneglassoflemonjuicewithhoney));
                textView21.setText(getResources().getString(R.string.Brownbreadvegsandwich));
                textView22.setText(getResources().getString(R.string.fourWalnuts));
                textView23.setText(getResources().getString(R.string.leafygreenssoupbroccolispinachlettuce));
                textView24.setText(getResources().getString(R.string.Pineappleslices));
                textView25.setVisibility(View.GONE);
                DailyMeal dailyMeal2 = dailyMeal;
                break;
        }
        return inflate;
    }

    public boolean onOptionsItemSelected(MenuItem menuItem) {
        if (menuItem.getItemId() == 16908332) {
            if (this.interstitial.isLoaded()) {
                this.interstitial.show();
            }
            getFragmentManager().popBackStack();
        }
        return super.onOptionsItemSelected(menuItem);
    }
}
